CREATE TABLE "TB_ORDER"
(
    "ID_ORDER" LONG PRIMARY KEY,
    "ID_USER" LONG NOT NULL,
     FOREIGN KEY ("ID_USER") REFERENCES "TB_USER" ("ID_USER"),
    "STATUS" VARCHAR2 CHECK("STATUS" IN ('OPEN', 'PAID', 'CLOSED','CANCELLED')),
    "ITEMS" LONG,
    "OPEN_DATE" DATE,
    "CLOSE_DATE" DATE,
    "DISCOUNT" INT NOT NULL,
    "VALUE" NUMBER(15, 6) NOT NULL,
);