CREATE TABLE "TB_ORDER_ITEM"
  (
      "ID_ITEM" LONG PRIMARY KEY,
      "ID_FLOWER" LONG NOT NULL,
      FOREIGN KEY ("ID_ORDER") REFERENCES "TB_ORDER" ("ID_ORDER"),
      "ID_FLOWER" LONG NOT NULL,
      FOREIGN KEY ("ID_FLOWER") REFERENCES "TB_FLOWER" ("ID_FLOWER"),
      "COUNT" INT NOT NULL
  );