CREATE sequence "ORDER_ITEM_SG"

CREATE TABLE "TB_ORDER_ITEM"
  (
      "ID_ITEM" INT PRIMARY KEY,
      "ID_ORDER" INT NOT NULL,
      FOREIGN KEY ("ID_ORDER") REFERENCES "TB_ORDER" ("ID_ORDER"),
      "ID_FLOWER" INT NOT NULL,
      FOREIGN KEY ("ID_FLOWER") REFERENCES "TB_FLOWERS" ("ID"),
      "COUNT" INT NOT NULL
  );